// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ZOdEAg7t1UfKd_n7_wonnDJA-6X9zJg',
    appId: '1:71244676159:web:481d374fd302bf88b28c8a',
    messagingSenderId: '71244676159',
    projectId: 'wisme-app',
    authDomain: 'wisme-app.firebaseapp.com',
    storageBucket: 'wisme-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ZOdEAg7t1UfKd_n7_wonnDJA-6X9zJg',
    appId: '1:71244676159:android:481d374fd302bf88b28c8a',
    messagingSenderId: '71244676159',
    projectId: 'wisme-app',
    storageBucket: 'wisme-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ZOdEAg7t1UfKd_n7_wonnDJA-6X9zJg',
    appId: '1:71244676159:ios:481d374fd302bf88b28c8a',
    messagingSenderId: '71244676159',
    projectId: 'wisme-app',
    storageBucket: 'wisme-app.appspot.com',
    iosBundleId: 'com.example.wismeApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ZOdEAg7t1UfKd_n7_wonnDJA-6X9zJg',
    appId: '1:71244676159:macos:481d374fd302bf88b28c8a',
    messagingSenderId: '71244676159',
    projectId: 'wisme-app',
    storageBucket: 'wisme-app.appspot.com',
    iosBundleId: 'com.example.wismeApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ZOdEAg7t1UfKd_n7_wonnDJA-6X9zJg',
    appId: '1:71244676159:web:481d374fd302bf88b28c8a',
    messagingSenderId: '71244676159',
    projectId: 'wisme-app',
    authDomain: 'wisme-app.firebaseapp.com',
    storageBucket: 'wisme-app.appspot.com',
  );
}
