// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHODOy0bNcbxZ4IZqyQYYl-4ZLIV9TGRY',
    appId: '1:3043141516:web:fde5093af66e808da758a9',
    messagingSenderId: '3043141516',
    projectId: 'wisme-research-app',
    authDomain: 'wisme-research-app.firebaseapp.com',
    storageBucket: 'wisme-research-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7QjTJWh32nD75OtjvRQF7tcdZg3WhM5s',
    appId: '1:3043141516:android:2753a40d85fc13f8a758a9',
    messagingSenderId: '3043141516',
    projectId: 'wisme-research-app',
    storageBucket: 'wisme-research-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhx2fiJbaFgnqnWbCLNz82YI04zBMf-I0',
    appId: '1:3043141516:ios:a3ea89e63a6c7e13a758a9',
    messagingSenderId: '3043141516',
    projectId: 'wisme-research-app',
    storageBucket: 'wisme-research-app.firebasestorage.app',
    iosBundleId: 'com.example.wismeResearchDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhx2fiJbaFgnqnWbCLNz82YI04zBMf-I0',
    appId: '1:3043141516:ios:a3ea89e63a6c7e13a758a9',
    messagingSenderId: '3043141516',
    projectId: 'wisme-research-app',
    storageBucket: 'wisme-research-app.firebasestorage.app',
    iosBundleId: 'com.example.wismeResearchDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHODOy0bNcbxZ4IZqyQYYl-4ZLIV9TGRY',
    appId: '1:3043141516:web:cb35e77512691b9aa758a9',
    messagingSenderId: '3043141516',
    projectId: 'wisme-research-app',
    authDomain: 'wisme-research-app.firebaseapp.com',
    storageBucket: 'wisme-research-app.firebasestorage.app',
  );
}

/*
Platform  Firebase App Id
web       1:3043141516:web:fde5093af66e808da758a9
android   1:3043141516:android:2753a40d85fc13f8a758a9
ios       1:3043141516:ios:a3ea89e63a6c7e13a758a9
macos     1:3043141516:ios:a3ea89e63a6c7e13a758a9
windows   1:3043141516:web:cb35e77512691b9aa758a9
*/